# Generated by Django 5.1.5 on 2025-03-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disucssionforumapp', '0002_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='timer_duration',
        ),
    ]
